// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev server dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "server/schema.server",
  migrations: {
    path: "server/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
